name: Render Jupyter Notebook

on: [push]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Jupyter
      run: |
        python -m pip install --upgrade pip
        pip install jupyter

    - name: Render Notebook
      run: |
        jupyter nbconvert --to html my_notebook.ipynb
      
    - name: Commit and push rendered HTML
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add my_notebook.html
        git commit -m 'Render notebook to HTML'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
